main  branch ci changes keep reslove branch conflict!

diff --git a/.github/workflows/ci-checks.yml b/.github/workflows/ci-checks.yml
--- a/.github/workflows/ci-checks.yml
+++ b/.github/workflows/ci-checks.yml
@@ -4,19 +4,19 @@ on: [push, pull_request, workflow_dispatch]
 
 jobs:
   ls_linting:
-      runs-on: ubuntu-latest
-      steps:  
-        - uses: actions/checkout@v4
-        - uses: ls-lint/action@v2.2.3
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ls-lint/action@v2.2.3
 
   md_formatting:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-    - uses: nosborn/github-action-markdown-cli@v3.3.0
-      with:
-        files: .
-        config_file: .markdownlint.yml
+      - uses: actions/checkout@v4
+      - uses: nosborn/github-action-markdown-cli@v3.3.0
+        with:
+          files: .
+          config_file: .markdownlint.yml
 
   py_formatting:
     runs-on: ubuntu-latest
@@ -44,38 +44,33 @@ jobs:
         if: always()
       - name: install pylint
         run: |
-          python -  m pip install --upgrade pip
+          python -m pip install --upgrade pip
           pip install pylint
         shell: bash
       - name: Python - Check Linting - pylint
-        run: "pylint solutions tests  || echo '::warning title=Pylint Error(s)::Discuss solutions and trade-offs in code review.'"
+        run: "pylint solutions tests || echo '::warning title=Pylint Error(s)::Discuss solutions and trade-offs in code review.'"
         shell: bash
 
   py_tests:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      
+
       - name: python version
         run: python --version
         shell: bash
-      
+
       - name: Check for test files
         id: check_tests
         run: |
-          test_files=$(find ./solutions/tests -type f -name "test_*.py")
-          if [ -n "$test_files" ]; then
-            echo "Found test files:"
-            echo "$test_files"
+          if find . -type f -name "test_*.py" | grep -q .; then
             echo "has_tests=true" >> $GITHUB_OUTPUT
           else
-            echo "No test files found matching pattern ./solutions/tests/test_*.py"
             echo "has_tests=false" >> $GITHUB_OUTPUT
           fi
         shell: bash
-      
+
       - name: Python - Run Tests
         if: steps.check_tests.outputs.has_tests == 'true'
         run: python -m unittest
         shell: bash
-
