Update ci-checks.yml

diff --git a/.github/workflows/ci-checks.yml b/.github/workflows/ci-checks.yml
--- a/.github/workflows/ci-checks.yml
+++ b/.github/workflows/ci-checks.yml
@@ -1,29 +1,22 @@
 name: ET CI Checks
 
-on: 
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
-  workflow_dispatch:
+on: [push, pull_request, workflow_dispatch]
 
 jobs:
   ls_linting:
-    runs-on: ubuntu-latest
-    steps:  
-      - uses: actions/checkout@v4
-      - uses: ls-lint/action@v2.2.3
+      runs-on: ubuntu-latest
+      steps:  
+        - uses: actions/checkout@v4
+        - uses: ls-lint/action@v2.2.3
 
   md_formatting:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-      - uses: nosborn/github-action-markdown-cli@v3.3.0
-        with:
-          files: .
-          config_file: .markdownlint.yml
+    - uses: actions/checkout@v4
+    - uses: nosborn/github-action-markdown-cli@v3.3.0
+      with:
+        files: .
+        config_file: .markdownlint.yml
 
   py_formatting:
     runs-on: ubuntu-latest
@@ -51,33 +44,34 @@ jobs:
         if: always()
       - name: install pylint
         run: |
-          python -m pip install --upgrade pip
+          python -  m pip install --upgrade pip
           pip install pylint
         shell: bash
       - name: Python - Check Linting - pylint
-        run: "pylint solutions tests || echo '::warning title=Pylint Error(s)::Discuss solutions and trade-offs in code review.'"
+        run: "pylint solutions tests  || echo '::warning title=Pylint Error(s)::Discuss solutions and trade-offs in code review.'"
         shell: bash
 
   py_tests:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-
-      # Determine if only Markdown files were changed
-      - name: Check for non-Markdown file changes
-        id: check_files
+      
+      - name: python version
+        run: python --version
+        shell: bash
+      
+      - name: Check for test files
+        id: check_tests
         run: |
-          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
-          if ! grep -qv '\.md$' changed_files.txt; then
-            echo "Only Markdown files changed. Skipping py_tests."
-            echo "skip=true" >> $GITHUB_ENV
+          if find . -type f -name "test_*.py" | grep -q .; then
+            echo "has_tests=true" >> $GITHUB_OUTPUT
           else
-            echo "Non-Markdown files changed. Proceeding with py_tests."
-            echo "skip=false" >> $GITHUB_ENV
-
-      # Run Python tests only if non-Markdown files are changed
+            echo "has_tests=false" >> $GITHUB_OUTPUT
+          fi
+        shell: bash
+      
       - name: Python - Run Tests
-        if: env.skip == 'false'
+        if: steps.check_tests.outputs.has_tests == 'true'
         run: python -m unittest
         shell: bash
 
